x = 100
try:
  print(x)
except:
  print("Ocurrió un error")
finally:
  print("Finalizó la ejecución")